language: java
sudo: false
jdk:
  - oraclejdk8
branches:
  only:
    - master
addons:
  sonarqube:
    organization: "domagojlatecki-github"
    token: '$SONAR_TOKEN'
    branches:
      only:
        - master
script:
  - mvn clean test jacoco:report package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
